--
-- @lc app=leetcode id=183 lang=mysql
--
-- [183] Customers Who Never Order
--
-- https://leetcode.com/problems/customers-who-never-order/description/
--
-- database
-- Easy (42.30%)
-- Total Accepted:    87.2K
-- Total Submissions: 205.8K
-- Testcase Example:  '{"headers": {"Customers": ["Id", "Name"], "Orders": ["Id", "CustomerId"]}, "rows": {"Customers": [[1, "Joe"], [2, "Henry"], [3, "Sam"], [4, "Max"]], "Orders": [[1, 3], [2, 1]]}}'
--
-- Suppose that a website contains two tables, the Customers table and the
-- Orders table. Write a SQL query to find all customers who never order
-- anything.
-- 
-- Table: Customers.
-- 
-- 
-- +----+-------+
-- | Id | Name  |
-- +----+-------+
-- | 1  | Joe   |
-- | 2  | Henry |
-- | 3  | Sam   |
-- | 4  | Max   |
-- +----+-------+
-- 
-- 
-- Table: Orders.
-- 
-- 
-- +----+------------+
-- | Id | CustomerId |
-- +----+------------+
-- | 1  | 3          |
-- | 2  | 1          |
-- +----+------------+
-- 
-- 
-- Using the above tables as example, return the following:
-- 
-- 
-- +-----------+
-- | Customers |
-- +-----------+
-- | Henry     |
-- | Max       |
-- +-----------+
-- 
-- 
--
# Write your MySQL query statement below
SELECT t1.Name as Customers FROM Customers as t1 LEFT JOIN Orders as t2 ON t1.Id = t2.CustomerId WHERE t2.CustomerId is null

-- SELECT t1.Name as Customers FROM Customers as t1 
-- WHERE (SELECT count(1) as num FROM Orders as t2 WHERE t2.CustomerId = t1.Id) = 0
